### ISSUE TITLE
PostMarketOS arm64 compile error

### ISSUE THREAD

**Issue by Nandor21** [nerva-project/nerva#6]
I am encountering an issue while trying to build the project on postmarketOS (which is Alpine-based) using an ARM64 CPU. Despite having installed or built all necessary dependencies and libraries, I am getting the following linking error:
[ 89%] Built target wallet
[ 89%] Built target cryptonote_protocol
[ 90%] Linking CXX executable ../../bin/nerva-wallet-rpc
[ 91%] Linking CXX executable ../../bin/nerva-wallet-cli
/usr/lib/gcc/aarch64-alpine-linux-musl/14.2.0/../../../../aarch64-alpine-linux-musl/bin/ld: ../common/libcommon.a(stack_trace.cpp.o): in function `tools::log_stack_trace(char const*)':
stack_trace.cpp:(.text+0x718): undefined reference to `el::base::debug::StackTrace::generateNew()'
/usr/lib/gcc/aarch64-alpine-linux-musl/14.2.0/../../../../aarch64-alpine-linux-musl/bin/ld: stack_trace.cpp:(.text+0x724): undefined reference to `el::base::debug::operator<<(std::ostream&, el::base::debug::StackTrace const&)'
/usr/lib/gcc/aarch64-alpine-linux-musl/14.2.0/../../../../aarch64-alpine-linux-musl/bin/ld: ../common/libcommon.a(stack_trace.cpp.o): in function `tools::log_stack_trace(char const*)':
stack_trace.cpp:(.text+0x718): undefined reference to `el::base::debug::StackTrace::generateNew()'
/usr/lib/gcc/aarch64-alpine-linux-musl/14.2.0/../../../../aarch64-alpine-linux-musl/bin/ld: stack_trace.cpp:(.text+0x724): undefined reference to `el::base::debug::operator<<(std::ostream&, el::base::debug::StackTrace const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [src/wallet/CMakeFiles/wallet_rpc_server.dir/build.make:141: bin/nerva-wallet-rpc] Error 1
make[1]: *** [CMakeFiles/Makefile2:2032: src/wallet/CMakeFiles/wallet_rpc_server.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
collect2: error: ld returned 1 exit status
make[2]: *** [src/simplewallet/CMakeFiles/simplewallet.dir/build.make:141: bin/nerva-wallet-cli] Error 1
make[1]: *** [CMakeFiles/Makefile2:2283: src/simplewallet/CMakeFiles/simplewallet.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

System and Environment Information:
CPU: 
Architecture:            aarch64
  CPU op-mode(s):        32-bit, 64-bit
  Byte Order:            Little Endian
CPU(s):                  4
  On-line CPU(s) list:   0-3
Vendor ID:               ARM
  Model name:            Cortex-A53
    Model:               0
    Thread(s) per core:  1
    Core(s) per cluster: 4
    Socket(s):           -
    Cluster(s):          1
    Stepping:            r0p0
    CPU(s) scaling MHz:  80%
    CPU max MHz:         998.4000
    CPU min MHz:         200.0000
    BogoMIPS:            38.00
    Flags:               fp asimd evtstrm crc32 cpuid
OS:
  PostMarketOS (Alpine based)
  kernel: 6.6.0-msm8916
Make:
GNU Make 4.4.1
Built for aarch64-alpine-linux-musl
Copyright (C) 1988-2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
GCC and G++:
  gcc (Alpine 14.2.0) 14.2.0
 g++ (Alpine 14.2.0) 14.2.0

Steps Taken:

    Installed all necessary dependencies and libraries
    Attempted to troubleshoot by updating libraries and configuration
    nothing worked :(

**Comment by Nandor21** [comment]
[ 94%] Built target multisig
[ 95%] Built target cryptonote_core
[ 95%] Built target obj_wallet
[ 97%] Linking CXX static library ../../lib/libwallet.a
[ 97%] Built target wallet
[ 98%] Building CXX object src/wallet/CMakeFiles/wallet_rpc_server.dir/wallet_rpc_server.cpp.o
In file included from /home/nandor/sd/nerva/src/wallet/wallet2.h:50,
                 from /home/nandor/sd/nerva/src/wallet/wallet_rpc_server.h:41,
                 from /home/nandor/sd/nerva/src/wallet/wallet_rpc_server.cpp:41:
/home/nandor/sd/nerva/src/cryptonote_basic/cryptonote_basic_impl.h:43:29: warning: 'template<class _Arg, class _Result> struct std::unary_function' is deprecated [-Wdeprecated-declarations]
   43 |   struct array_hasher: std::unary_function<t_array&, std::size_t>
      |                             ^~~~~~~~~~~~~~
In file included from /usr/include/c++/14.2.0/bits/refwrap.h:39,
                 from /usr/include/c++/14.2.0/vector:68,
                 from /usr/include/boost/format.hpp:17,
                 from /home/nandor/sd/nerva/src/wallet/wallet_rpc_server.cpp:31:
/usr/include/c++/14.2.0/bits/stl_function.h:117:12: note: declared here
  117 |     struct unary_function
      |            ^~~~~~~~~~~~~~
/home/nandor/sd/nerva/src/wallet/wallet_rpc_server.cpp: In member function 'bool tools::wallet_rpc_server::on_get_account_tags(const tools::wallet_rpc::COMMAND_RPC_GET_ACCOUNT_TAGS::request&, tools::wallet_rpc::COMMAND_RPC_GET_ACCOUNT_TAGS::response&, epee::json_rpc::error&, const connection_context*)':
/home/nandor/sd/nerva/src/wallet/wallet_rpc_server.cpp:658:53: warning: loop variable 'p' of type 'const std::pair<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >&' binds to a temporary constructed from type 'const std::pair<const std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >' [-Wrange-loop-construct]
  658 |     for (const std::pair<std::string, std::string>& p : account_tags.first)
      |                                                     ^
/home/nandor/sd/nerva/src/wallet/wallet_rpc_server.cpp:658:53: note: use non-reference type 'const std::pair<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >' to make the copy explicit or 'const std::pair<const std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >&' to prevent copying
[100%] Linking CXX executable ../../bin/nerva-wallet-rpc
/usr/lib/gcc/aarch64-alpine-linux-musl/14.2.0/../../../../aarch64-alpine-linux-musl/bin/ld: ../common/libcommon.a(stack_trace.cpp.o): in function `tools::log_stack_trace(char const*)':
stack_trace.cpp:(.text+0x718): undefined reference to `el::base::debug::StackTrace::generateNew()'
/usr/lib/gcc/aarch64-alpine-linux-musl/14.2.0/../../../../aarch64-alpine-linux-musl/bin/ld: stack_trace.cpp:(.text+0x724): undefined reference to `el::base::debug::operator<<(std::ostream&, el::base::debug::StackTrace const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [src/wallet/CMakeFiles/wallet_rpc_server.dir/build.make:141: bin/nerva-wallet-rpc] Error 1
make[1]: *** [CMakeFiles/Makefile2:2032: src/wallet/CMakeFiles/wallet_rpc_server.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

**Comment by Nandor21** [comment]
alpine not support systemd to compile the project successfuly but i working on it

**Comment by Sn1F3rt** [comment]
Hi. Can you try using the latest version from `master` and try to build using `make release-noaes`?

**Comment by Nandor21** [comment]
> Hi. Can you try using the latest version from `master` and try to build using `make release-noaes`?

Yes i used the master and in cmake i disable-t the aes support but the main problem is the libcommon because this need the systemd and reinstalled postmarketos with systemd (i dont tryed compile the nerva project). I try next day what you say maybe its work

**Comment by Nandor21** [comment]
> Hi. Can you try using the latest version from `master` and try to build using `make release-noaes`?

it not worked maybe my device cant handle the systemd and thats why i can compile i'm done, i tryed solve my problem and the last thing was i kown make was waiting someone was kown how solve my issue. Thanks your time and help

**Comment by Sn1F3rt** [comment]
No worries. We're working towards reviving the project and making everything work on the mainstream OSes first. Once that's done, we could look into supporting miscellaneous OS, including this one.
